#!/usr/bin/env python3
# Copyright 2014 icasdri
__author__ = "icasdri"

# Main script for thunderbird notifications example (part of user-python-daemon)
if __name__ == "__main__":
    from user_python_daemon.examples.thunderbird_notifications import main
    main()
