#!/usr/bin/env python3
# Copyright 2014 icasdri
__author__ = "icasdri"

# user-python-daemon main script
if __name__ == "__main__":
    from user_python_daemon.user_python_daemon import main
    main()
